### PR TITLE
PyPI, travis, test coverage, and dockerfile

### PR DESCRIPTION
**Pull request by sbellem**

### CODE REVIEW

**Comment by vrde** [comment]
:+1: looks good to me, let's wait for @r-marques feedback.

**Comment by r-marques** [comment]
since we are at it lets use semantic versioning like we do with bigchaindb and tag the first release as v0.1.0

**Comment by sbellem** [comment]
yes, thanks

**Comment by sbellem** [comment]
I will close this PR so that PR #2 with branch 0.1.0 replaces it.

**Pull request closed without merging**
